services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../framework/*'

  Command\:
    resource: '../commands/*'

  Controller\:
    resource: '../controllers/*'
#    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
